-   repo: /Users/marick/src/pre-commit-hooks
    sha: 569f6300cbbedf177c56eda8023350620998ff8f
    stages:
    - push
    hooks:
    -   id: only-branch-pushes
        args:
        - master|production
