-   repo: /Users/marick/src/pre-commit-hooks
    sha: b7bce722087d477f533e49ccf2dfe65906d8502b
    stages:
    - push
    hooks:
    -   id: only-branch-pushes
        args:
        - master|production
